/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mensa;

/**
 *
 * @author Usuario
 */
public class Envio extends javax.swing.JFrame {

	VistaPrevia vp;
	Opciones op;

    /**
     * Creates new form Envio
     */
    public Envio() {
        initComponents();
        contadorDeEventos=0;
	this.vp = new VistaPrevia();
	this.op = new Opciones(this);
        
        // Modelo para edición dinámica de la lista
        this.listRemitentes.setModel(new javax.swing.DefaultListModel());
    }

   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                bGDestino = new javax.swing.ButtonGroup();
                bGOrganizacion = new javax.swing.ButtonGroup();
                bGDestinoTab = new javax.swing.ButtonGroup();
                jLabel1 = new javax.swing.JLabel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                TF_Destino = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                TF_DireccionPostal = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                rbProvincial = new javax.swing.JRadioButton();
                rbNacional = new javax.swing.JRadioButton();
                rbInternacional = new javax.swing.JRadioButton();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                cbProvincia = new javax.swing.JComboBox();
                jLabel7 = new javax.swing.JLabel();
                cbPais = new javax.swing.JComboBox();
                tfMunicipio = new javax.swing.JTextField();
                jPanel4 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                TF_Remitente = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                tfRemDireccion = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                cbOrganizacion = new javax.swing.JComboBox();
                checkClienteRegistrado = new javax.swing.JCheckBox();
                jLabel11 = new javax.swing.JLabel();
                tfCodigoCliente = new javax.swing.JTextField();
                bCodigoClienteOK = new javax.swing.JButton();
                jSeparator2 = new javax.swing.JSeparator();
                jScrollPane1 = new javax.swing.JScrollPane();
                listRemitentes = new javax.swing.JList();
                bAddRemitente = new javax.swing.JButton();
                bBorrarRemitente = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                BT_Opciones = new javax.swing.JButton();
                BT_VistaPrevia = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jPanel3 = new javax.swing.JPanel();
                jPanel6 = new javax.swing.JPanel();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                jMenuItem1 = new javax.swing.JMenuItem();
                jSeparator1 = new javax.swing.JPopupMenu.Separator();
                jMenuItem2 = new javax.swing.JMenuItem();
                jMenu3 = new javax.swing.JMenu();
                jMenu4 = new javax.swing.JMenu();
                rbmiProvincial = new javax.swing.JRadioButtonMenuItem();
                rbmiNacional = new javax.swing.JRadioButtonMenuItem();
                rbmiInternacional = new javax.swing.JRadioButtonMenuItem();
                menuOrganizacion = new javax.swing.JMenu();
                rbmiPersonal = new javax.swing.JRadioButtonMenuItem();
                rbmiEmpresarial = new javax.swing.JRadioButtonMenuItem();
                rbmiPublica = new javax.swing.JRadioButtonMenuItem();
                jMenu2 = new javax.swing.JMenu();
                jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
                jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Mensa: Envío de mensjes");

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel1.setText("Mensa: Envío de mensajes");

                jLabel2.setText("Nombre y apellidos:");

                jLabel3.setText("Dirección postal:");

                jLabel4.setText("Destino:");

                bGDestinoTab.add(rbProvincial);
                rbProvincial.setSelected(true);
                rbProvincial.setText("Provincial");
                rbProvincial.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                rbProvincialItemStateChanged(evt);
                        }
                });
                rbProvincial.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbProvincialActionPerformed(evt);
                        }
                });

                bGDestinoTab.add(rbNacional);
                rbNacional.setText("Nacional");
                rbNacional.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                rbNacionalItemStateChanged(evt);
                        }
                });
                rbNacional.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbNacionalActionPerformed(evt);
                        }
                });

                bGDestinoTab.add(rbInternacional);
                rbInternacional.setText("Internacional");
                rbInternacional.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                rbInternacionalItemStateChanged(evt);
                        }
                });
                rbInternacional.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbInternacionalActionPerformed(evt);
                        }
                });

                jLabel5.setText("Municipio");

                jLabel6.setText("Provincia");

                cbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asturias", "Cantabria", "León", "Lugo" }));
                cbProvincia.setEnabled(false);

                jLabel7.setText("País");

                cbPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "España", "Francia", "Portugal" }));
                cbPais.setEnabled(false);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbNacional)
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbInternacional)
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TF_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(rbProvincial))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(TF_DireccionPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfMunicipio)))))
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TF_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(TF_DireccionPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbProvincial)
                                        .addComponent(jLabel5)
                                        .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbNacional)
                                        .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(rbInternacional)
                                        .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(46, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Destinatario", jPanel1);

                jLabel8.setText("Nombre y apellidos:");

                jLabel9.setText("Dirección postal:");

                jLabel10.setText("Organización:");

                cbOrganizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal", "Empresarial", "Publica" }));
                cbOrganizacion.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cbOrganizacionItemStateChanged(evt);
                        }
                });

                checkClienteRegistrado.setText("Cliente registrado");
                checkClienteRegistrado.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                checkClienteRegistradoItemStateChanged(evt);
                        }
                });

                jLabel11.setText("Código de cliente");

                tfCodigoCliente.setEnabled(false);
                tfCodigoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                tfCodigoClienteKeyTyped(evt);
                        }
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfCodigoClienteKeyReleased(evt);
                        }
                });

                bCodigoClienteOK.setIcon(new javax.swing.ImageIcon("C:\\Users\\aleja\\Downloads\\iconCheck.png")); // NOI18N
                bCodigoClienteOK.setEnabled(false);
                bCodigoClienteOK.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bCodigoClienteOKActionPerformed(evt);
                        }
                });

                listRemitentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                listRemitentes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                                listRemitentesValueChanged(evt);
                        }
                });
                jScrollPane1.setViewportView(listRemitentes);

                bAddRemitente.setText("Añadir remitente");
                bAddRemitente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bAddRemitenteActionPerformed(evt);
                        }
                });

                bBorrarRemitente.setText("Borrar remitente");
                bBorrarRemitente.setEnabled(false);
                bBorrarRemitente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bBorrarRemitenteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(TF_Remitente, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(jLabel10))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(tfRemDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(checkClienteRegistrado)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(bCodigoClienteOK, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(bAddRemitente)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(bBorrarRemitente)))))
                                .addContainerGap())
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(checkClienteRegistrado)
                                                .addComponent(jLabel11)
                                                .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(bCodigoClienteOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TF_Remitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(tfRemDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(cbOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(bBorrarRemitente)
                                                .addGap(1, 1, 1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(bAddRemitente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Remitente", jPanel4);

                BT_Opciones.setText("Opciones");
                BT_Opciones.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_OpcionesActionPerformed(evt);
                        }
                });

                BT_VistaPrevia.setText("Vista Previa");
                BT_VistaPrevia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_VistaPreviaActionPerformed(evt);
                        }
                });

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane2.setViewportView(jTextArea1);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(BT_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                                                .addComponent(BT_VistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BT_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BT_VistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Etiqueta", jPanel5);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 600, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 292, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Ruta y tarifa", jPanel3);

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 600, Short.MAX_VALUE)
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 292, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Pago", jPanel6);

                jMenu1.setText("Envío");

                jMenuItem1.setText("Nuevo envío");
                jMenu1.add(jMenuItem1);
                jMenu1.add(jSeparator1);

                jMenuItem2.setText("Salir");
                jMenu1.add(jMenuItem2);

                jMenuBar1.add(jMenu1);

                jMenu3.setText("Ámbito");

                jMenu4.setText("Destino");

                bGDestino.add(rbmiProvincial);
                rbmiProvincial.setSelected(true);
                rbmiProvincial.setText("Provincial");
                rbmiProvincial.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbmiProvincialActionPerformed(evt);
                        }
                });
                jMenu4.add(rbmiProvincial);

                bGDestino.add(rbmiNacional);
                rbmiNacional.setText("Nacional");
                rbmiNacional.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbmiNacionalActionPerformed(evt);
                        }
                });
                jMenu4.add(rbmiNacional);

                bGDestino.add(rbmiInternacional);
                rbmiInternacional.setText("Internacional");
                rbmiInternacional.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbmiInternacionalActionPerformed(evt);
                        }
                });
                jMenu4.add(rbmiInternacional);

                jMenu3.add(jMenu4);

                menuOrganizacion.setText("Organización");

                bGOrganizacion.add(rbmiPersonal);
                rbmiPersonal.setSelected(true);
                rbmiPersonal.setText("Personal");
                rbmiPersonal.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbmiPersonalActionPerformed(evt);
                        }
                });
                menuOrganizacion.add(rbmiPersonal);

                bGOrganizacion.add(rbmiEmpresarial);
                rbmiEmpresarial.setText("Empresarial");
                rbmiEmpresarial.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbmiEmpresarialActionPerformed(evt);
                        }
                });
                menuOrganizacion.add(rbmiEmpresarial);

                bGOrganizacion.add(rbmiPublica);
                rbmiPublica.setText("Pública");
                rbmiPublica.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbmiPublicaActionPerformed(evt);
                        }
                });
                menuOrganizacion.add(rbmiPublica);

                jMenu3.add(menuOrganizacion);

                jMenuBar1.add(jMenu3);

                jMenu2.setText("Condiciones");

                jCheckBoxMenuItem1.setSelected(true);
                jCheckBoxMenuItem1.setText("Frágil");
                jMenu2.add(jCheckBoxMenuItem1);

                jCheckBoxMenuItem2.setSelected(true);
                jCheckBoxMenuItem2.setText("Urgente");
                jMenu2.add(jCheckBoxMenuItem2);

                jMenuBar1.add(jMenu2);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private int contadorDeEventos;
    private void Traza(String msg)
    {
        contadorDeEventos=contadorDeEventos+1;
        System.out.println("Evento:"+contadorDeEventos+" "+msg);
    }
    
    private void rbmiNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiNacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbmiNacionalActionPerformed");
        this.rbNacional.setSelected(this.rbmiNacional.isSelected());
    }//GEN-LAST:event_rbmiNacionalActionPerformed

    private void rbmiProvincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiProvincialActionPerformed
        // TODO add your handling code here:
        Traza("rbmiProvincialActionPerformed");
        this.rbProvincial.setSelected(this.rbmiProvincial.isSelected());
    }//GEN-LAST:event_rbmiProvincialActionPerformed

    private void rbmiInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiInternacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbmiInternacionalActionPerformed");
        this.rbInternacional.setSelected(this.rbmiInternacional.isSelected());
    }//GEN-LAST:event_rbmiInternacionalActionPerformed

    private void rbProvincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProvincialActionPerformed
        // TODO add your handling code here:
        Traza("rbProvincialActionPerformed");
        this.rbmiProvincial.setSelected(this.rbProvincial.isSelected());
    }//GEN-LAST:event_rbProvincialActionPerformed

    private void rbNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbNacionalActionPerformed");
        this.rbmiNacional.setSelected(this.rbNacional.isSelected());
    }//GEN-LAST:event_rbNacionalActionPerformed

    private void rbInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInternacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbInternacionalActionPerformed");
        this.rbmiInternacional.setSelected(this.rbInternacional.isSelected());
    }//GEN-LAST:event_rbInternacionalActionPerformed

    private void rbInternacionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbInternacionalItemStateChanged
        // TODO add your handling code here:
        Traza("rbInternacionalItemStateChanged");
        this.cbPais.setEnabled(this.rbInternacional.isSelected());
    }//GEN-LAST:event_rbInternacionalItemStateChanged

    private void rbProvincialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbProvincialItemStateChanged
        // TODO add your handling code here:       
        Traza("rbProvincialItemStateChanged");
        MunicipioSetEnabled();       
    }//GEN-LAST:event_rbProvincialItemStateChanged

    private void rbNacionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNacionalItemStateChanged
        // TODO add your handling code here:    
        Traza("rbNacionalItemStateChanged");
        MunicipioSetEnabled();
        this.cbProvincia.setEnabled(this.rbNacional.isSelected());
    }//GEN-LAST:event_rbNacionalItemStateChanged

    private void checkClienteRegistradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkClienteRegistradoItemStateChanged
        // TODO add your handling code here:
        boolean cr=this.checkClienteRegistrado.isSelected();
        this.tfCodigoCliente.setEnabled(cr);
        this.TF_Remitente.setEnabled(!cr);
        this.tfRemDireccion.setEnabled(!cr);
        this.cbOrganizacion.setEnabled(!cr);
        this.menuOrganizacion.setEnabled(!cr);
    }//GEN-LAST:event_checkClienteRegistradoItemStateChanged

    private void SincronizaCBOrganizacion(int posSel)
    {
        this.cbOrganizacion.setSelectedIndex(posSel);
    }
    
    private void rbmiPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiPersonalActionPerformed
        // TODO add your handling code here:
        SincronizaCBOrganizacion(0);
    }//GEN-LAST:event_rbmiPersonalActionPerformed

    private void rbmiEmpresarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiEmpresarialActionPerformed
        // TODO add your handling code here:
        SincronizaCBOrganizacion(1);
    }//GEN-LAST:event_rbmiEmpresarialActionPerformed

    private void rbmiPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiPublicaActionPerformed
        // TODO add your handling code here:
        SincronizaCBOrganizacion(2);
    }//GEN-LAST:event_rbmiPublicaActionPerformed

    private void cbOrganizacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOrganizacionItemStateChanged
        // TODO add your handling code here:
        switch(this.cbOrganizacion.getSelectedIndex())
        {
            case 0: this.rbmiPersonal.setSelected(true); break;
            case 1: this.rbmiEmpresarial.setSelected(true); break;
            case 2: this.rbmiPublica.setSelected(true); break;
        }
    }//GEN-LAST:event_cbOrganizacionItemStateChanged

    private void tfCodigoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoClienteKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (c>='a' && c<='f') // Si c es minúscula, se pasa a muyúsculas
            c=(char)((int)c-(int)'a'+(int)'A');
   
        if (c>='A' && c<='F')
            evt.setKeyChar(c);
        else if (c>='0' && c<='9')
            evt.setKeyChar(c);
        else
            evt.setKeyChar('\0');
    }//GEN-LAST:event_tfCodigoClienteKeyTyped

    private void tfCodigoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoClienteKeyReleased
        // TODO add your handling code here:
        boolean CCOK=false;
        String CC=this.tfCodigoCliente.getText();
        if (CC.length()==7)
        {
            char PriChar=CC.charAt(0);
            if (PriChar>='0' && PriChar<='9')
                CCOK=true;
        }
        this.bCodigoClienteOK.setEnabled(CCOK);
    }//GEN-LAST:event_tfCodigoClienteKeyReleased

    private void bCodigoClienteOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCodigoClienteOKActionPerformed
        // TODO add your handling code here:
        this.TF_Remitente.setText("Un nombre y apelidos cualquiera");
        this.tfRemDireccion.setText("Una dirección cualquiera");
        this.cbOrganizacion.setSelectedIndex(1); // Empresarial
    }//GEN-LAST:event_bCodigoClienteOKActionPerformed

    private void bAddRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddRemitenteActionPerformed
        // TODO add your handling code here:

        // Crear la cadena a insertar
        String Pre="";
        switch(this.cbOrganizacion.getSelectedIndex())
        {
            case 0: Pre="Per"; break;
            case 1: Pre="Emp"; break;
            case 2: Pre="Pub"; break;                
        }
        String CI=Pre+": "+this.TF_Remitente.getText()+" ("+this.tfRemDireccion.getText()+") ";
        
        // Obtener el modelo
        javax.swing.DefaultListModel Model=(javax.swing.DefaultListModel)this.listRemitentes.getModel();
        
        // Insertar la cadena en el modelo
        Model.addElement(CI);
    }//GEN-LAST:event_bAddRemitenteActionPerformed

    private void bBorrarRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarRemitenteActionPerformed
        // TODO add your handling code here:
        
        // Obtener el modelo
        javax.swing.DefaultListModel Model=(javax.swing.DefaultListModel)this.listRemitentes.getModel();
        
        int Si=this.listRemitentes.getSelectedIndex(); // Obtiene el índice de la posición a borrar
        if (Si>=0) // Hay una fila seleccionada
        {
            Model.removeElementAt(Si); // Borra el elemento
            // Mantener la selección en su posición
            if(Model.size()==Si) // Se ha borrado el último elemento
                this.listRemitentes.setSelectedIndex(Si-1);
            else
                this.listRemitentes.setSelectedIndex(Si);
        }
    }//GEN-LAST:event_bBorrarRemitenteActionPerformed

    private void listRemitentesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRemitentesValueChanged
        // TODO add your handling code here:
        this.bBorrarRemitente.setEnabled(!this.listRemitentes.isSelectionEmpty());
    }//GEN-LAST:event_listRemitentesValueChanged

	
        private void BT_VistaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VistaPreviaActionPerformed
                // TODO add your handling code here:
//		this.vp.setDestinatario(TF_Destino.getText());
//		this.vp.setRemitente(TF_Remitente.getText());
		this.vp.setVisible(true);
        }//GEN-LAST:event_BT_VistaPreviaActionPerformed

        private void BT_OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_OpcionesActionPerformed
                // TODO add your handling code here:
		this.op.setVisible(true);
        }//GEN-LAST:event_BT_OpcionesActionPerformed

    // Método que activa el textField de municipio solo si está activado el envío provincial o nacional
    private int cMSE=0;
    private void MunicipioSetEnabled()
    {
        cMSE=cMSE+1;
        // Se activará el municipio si es un envío provincial o nacional
        System.out.println("MunicipioSetEnabled "+cMSE+" "+(this.rbProvincial.isSelected() || this.rbNacional.isSelected()));
        this.tfMunicipio.setEnabled(this.rbProvincial.isSelected() || this.rbNacional.isSelected());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Envio().setVisible(true);
            }
        });
    }
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton BT_Opciones;
        javax.swing.JButton BT_VistaPrevia;
        javax.swing.JTextField TF_Destino;
        javax.swing.JTextField TF_DireccionPostal;
        javax.swing.JTextField TF_Remitente;
        javax.swing.JButton bAddRemitente;
        javax.swing.JButton bBorrarRemitente;
        javax.swing.JButton bCodigoClienteOK;
        javax.swing.ButtonGroup bGDestino;
        javax.swing.ButtonGroup bGDestinoTab;
        javax.swing.ButtonGroup bGOrganizacion;
        javax.swing.JComboBox cbOrganizacion;
        javax.swing.JComboBox cbPais;
        javax.swing.JComboBox cbProvincia;
        javax.swing.JCheckBox checkClienteRegistrado;
        javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
        javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel10;
        javax.swing.JLabel jLabel11;
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel3;
        javax.swing.JLabel jLabel4;
        javax.swing.JLabel jLabel5;
        javax.swing.JLabel jLabel6;
        javax.swing.JLabel jLabel7;
        javax.swing.JLabel jLabel8;
        javax.swing.JLabel jLabel9;
        javax.swing.JMenu jMenu1;
        javax.swing.JMenu jMenu2;
        javax.swing.JMenu jMenu3;
        javax.swing.JMenu jMenu4;
        javax.swing.JMenuBar jMenuBar1;
        javax.swing.JMenuItem jMenuItem1;
        javax.swing.JMenuItem jMenuItem2;
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel3;
        javax.swing.JPanel jPanel4;
        javax.swing.JPanel jPanel5;
        javax.swing.JPanel jPanel6;
        javax.swing.JScrollPane jScrollPane1;
        javax.swing.JScrollPane jScrollPane2;
        javax.swing.JPopupMenu.Separator jSeparator1;
        javax.swing.JSeparator jSeparator2;
        javax.swing.JTabbedPane jTabbedPane1;
        javax.swing.JTextArea jTextArea1;
        javax.swing.JList listRemitentes;
        javax.swing.JMenu menuOrganizacion;
        javax.swing.JRadioButton rbInternacional;
        javax.swing.JRadioButton rbNacional;
        javax.swing.JRadioButton rbProvincial;
        javax.swing.JRadioButtonMenuItem rbmiEmpresarial;
        javax.swing.JRadioButtonMenuItem rbmiInternacional;
        javax.swing.JRadioButtonMenuItem rbmiNacional;
        javax.swing.JRadioButtonMenuItem rbmiPersonal;
        javax.swing.JRadioButtonMenuItem rbmiProvincial;
        javax.swing.JRadioButtonMenuItem rbmiPublica;
        javax.swing.JTextField tfCodigoCliente;
        javax.swing.JTextField tfMunicipio;
        javax.swing.JTextField tfRemDireccion;
        // End of variables declaration//GEN-END:variables
}
