/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dialogos;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author UO281827 // Rodriguez Lopez, Alejandro 
 */
public class Principal extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */
	public Principal() {
		initComponents();
		this.DFichero = new JFileChooser ();
		this.dp =new DatosPersonales ();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                BT_Informe = new javax.swing.JButton();
                BT_Borrar = new javax.swing.JButton();
                LB_Datos = new javax.swing.JLabel();
                PL_ColorMousePressed = new javax.swing.JPanel();
                BT_Fichero = new javax.swing.JButton();
                LB_Fichero = new javax.swing.JLabel();
                BT_DatosPersonales = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                LB_Nombre = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                LB_Edad = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                BT_Informe.setText("Informe");
                BT_Informe.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_InformeActionPerformed(evt);
                        }
                });

                BT_Borrar.setText("Borrar");
                BT_Borrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_BorrarActionPerformed(evt);
                        }
                });

                LB_Datos.setText("Datos");

                PL_ColorMousePressed.setBackground(new java.awt.Color(255, 255, 255));
                PL_ColorMousePressed.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                PL_ColorMousePressedMousePressed(evt);
                        }
                });

                javax.swing.GroupLayout PL_ColorMousePressedLayout = new javax.swing.GroupLayout(PL_ColorMousePressed);
                PL_ColorMousePressed.setLayout(PL_ColorMousePressedLayout);
                PL_ColorMousePressedLayout.setHorizontalGroup(
                        PL_ColorMousePressedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 212, Short.MAX_VALUE)
                );
                PL_ColorMousePressedLayout.setVerticalGroup(
                        PL_ColorMousePressedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                BT_Fichero.setText("Fichero");
                BT_Fichero.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_FicheroActionPerformed(evt);
                        }
                });

                BT_DatosPersonales.setText("Datos Personales");
                BT_DatosPersonales.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_DatosPersonalesActionPerformed(evt);
                        }
                });

                jLabel1.setText("Nombre:");

                jLabel3.setText("Edad:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(BT_Informe)
                                                .addGap(18, 18, 18)
                                                .addComponent(BT_Borrar)
                                                .addGap(18, 18, 18)
                                                .addComponent(LB_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(PL_ColorMousePressed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(BT_Fichero)
                                                        .addComponent(BT_DatosPersonales)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(LB_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                                                        .addComponent(LB_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LB_Fichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BT_Informe)
                                        .addComponent(BT_Borrar)
                                        .addComponent(LB_Datos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PL_ColorMousePressed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(BT_Fichero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BT_DatosPersonales)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(LB_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(LB_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(LB_Fichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void BT_InformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_InformeActionPerformed
                // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Problema en el informe.", "Informe", JOptionPane.WARNING_MESSAGE);
	//			   (null, Texto, Título, Tipo);
        }//GEN-LAST:event_BT_InformeActionPerformed

        private void BT_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BorrarActionPerformed
                // TODO add your handling code here:
	if (JOptionPane.showConfirmDialog(null, "¿Borrar contenido?", "Borrar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) ==
		JOptionPane.YES_OPTION) {
		this.LB_Datos.setText("null");
	}
        }//GEN-LAST:event_BT_BorrarActionPerformed

        private void PL_ColorMousePressedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PL_ColorMousePressedMousePressed
                // TODO add your handling code here:
	Color c = JColorChooser.showDialog(null, "Color del panel", this.PL_ColorMousePressed.getBackground()); 
	//			(null, Título, Color marcado por defecto (el actual))
	if(c != null) {
		this.PL_ColorMousePressed.setBackground(c);
	}
	
        }//GEN-LAST:event_PL_ColorMousePressedMousePressed

        private void BT_FicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_FicheroActionPerformed
                // TODO add your handling code here:
	if (this.DFichero.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
		this.LB_Fichero.setText(this.DFichero.getSelectedFile().getAbsolutePath());
	}
        }//GEN-LAST:event_BT_FicheroActionPerformed

        private void BT_DatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_DatosPersonalesActionPerformed
                // TODO add your handling code here:
	if (this.dp.showDialog()) {
		this.LB_Nombre.setText (this.dp.getNombre());
		this.LB_Edad.setText(String.format ("%d", 2022 - this.dp.getAnno()));
	}
        }//GEN-LAST:event_BT_DatosPersonalesActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Principal().setVisible(true);
			}
		});
	}

	//Referencia a JFileChooser
	private JFileChooser DFichero;

	//Referencia a Modal Personalizado
	private DatosPersonales dp;

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BT_Borrar;
        private javax.swing.JButton BT_DatosPersonales;
        private javax.swing.JButton BT_Fichero;
        private javax.swing.JButton BT_Informe;
        private javax.swing.JLabel LB_Datos;
        private javax.swing.JLabel LB_Edad;
        private javax.swing.JLabel LB_Fichero;
        private javax.swing.JLabel LB_Nombre;
        private javax.swing.JPanel PL_ColorMousePressed;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        // End of variables declaration//GEN-END:variables
}
