/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pintar;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Rodriguez Lopez, Alejandro // UO281827 
 */
public class Ventana extends javax.swing.JFrame {

	/**
	 * Creates new form Ventana
	 */
	public Ventana() {
		initComponents();
		this.pp = (PaintPanel) PP_Paint;	// Asignar ref
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                PP_Paint = new PaintPanel ();	// Escrito desde Properties > Code > Custom Creation Code.;
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                MI_Color = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new java.awt.GridLayout());

                PP_Paint.setBackground(new java.awt.Color(255, 255, 255));
                PP_Paint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                PP_PaintMouseDragged(evt);
                        }
                });

                javax.swing.GroupLayout PP_PaintLayout = new javax.swing.GroupLayout(PP_Paint);
                PP_Paint.setLayout(PP_PaintLayout);
                PP_PaintLayout.setHorizontalGroup(
                        PP_PaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                PP_PaintLayout.setVerticalGroup(
                        PP_PaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 275, Short.MAX_VALUE)
                );

                getContentPane().add(PP_Paint);

                jMenu1.setText("Formato");

                MI_Color.setText("Color");
                MI_Color.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                MI_ColorActionPerformed(evt);
                        }
                });
                jMenu1.add(MI_Color);

                jMenuBar1.add(jMenu1);

                setJMenuBar(jMenuBar1);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void MI_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ColorActionPerformed
                // TODO add your handling code here:
		Color c = JColorChooser.showDialog(null, "Elija color", this.pp.getColor());
		if (c != null) {
			this.pp.setColor(c);
			this.pp.repaint();
		}
        }//GEN-LAST:event_MI_ColorActionPerformed

        private void PP_PaintMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PP_PaintMouseDragged
                // TODO add your handling code here:
		this.pp.setX(evt.getX());
		this.pp.setY(evt.getY());
		this.pp.repaint();
        }//GEN-LAST:event_PP_PaintMouseDragged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ventana().setVisible(true);
			}
		});
	}

	private PaintPanel pp;	// Ref

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem MI_Color;
        private javax.swing.JPanel PP_Paint;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenuBar jMenuBar1;
        // End of variables declaration//GEN-END:variables
}
