/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author UO281827 // Rodriguez Lopez, Alejandro
 */
public class OtraVentana extends javax.swing.JFrame {
	/**
	 * Creates new form OtraVentana
	 */
	private OtraVentana () {
		initComponents();
	}

	/**
	 * Creates new form OtraVentana
	 * @param vp Reference to master window
	 */
	public OtraVentana (Ventana vp) {
		this();
		this.vp = vp;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                BT_Atras = new javax.swing.JButton();
                LB_Num = new javax.swing.JLabel();
                BT_Reset = new javax.swing.JButton();
                BT_ValorReset = new javax.swing.JButton();

                jLabel1.setText("Otra");

                BT_Atras.setText("Atrás");
                BT_Atras.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_AtrasActionPerformed(evt);
                        }
                });

                BT_Reset.setText("Reset");
                BT_Reset.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_ResetActionPerformed(evt);
                        }
                });

                BT_ValorReset.setText("Valor de Reset");
                BT_ValorReset.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BT_ValorResetActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(BT_Atras))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(LB_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 70, Short.MAX_VALUE)
                                                .addComponent(BT_ValorReset)
                                                .addGap(64, 64, 64)
                                                .addComponent(BT_Reset)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(LB_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BT_Atras)
                                        .addComponent(BT_Reset)
                                        .addComponent(BT_ValorReset))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void BT_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AtrasActionPerformed
                // TODO add your handling code here:
		this.setVisible(false);
        }//GEN-LAST:event_BT_AtrasActionPerformed

        private void BT_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ResetActionPerformed
                // TODO add your handling code here:
		if (this.vp.vr.TF_ValorReset.getText().isBlank() || this.vp.vr.TF_ValorReset.getText().isEmpty()) {
			this.vp.SL_Num.setValue(this.vp.SL_Num.getMaximum()/2);
		} else {
			this.vp.SL_Num.setValue(this.vp.vr.getValorReset());
		}
        }//GEN-LAST:event_BT_ResetActionPerformed

        private void BT_ValorResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ValorResetActionPerformed
                // TODO add your handling code here:
		this.vp.vr.setVisible(true);
        }//GEN-LAST:event_BT_ValorResetActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(OtraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(OtraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(OtraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(OtraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new OtraVentana().setVisible(true);
			}
		});
	}

	private Ventana vp;
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BT_Atras;
        private javax.swing.JButton BT_Reset;
        private javax.swing.JButton BT_ValorReset;
        javax.swing.JLabel LB_Num;
        private javax.swing.JLabel jLabel1;
        // End of variables declaration//GEN-END:variables
}
